version: '3.8'

services:
  test:
    build: .
    environment:
      - OPENAI_API_KEY=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
    command: pytest --cov=src --cov-report=xml --cov-report=html
